name: quiz_app
description: Cerebro Metron Quiz App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  confetti: ^0.7.0
  audioplayers: ^6.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#D0D3EE"
  image: assets/icons/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/card.png
    - assets/sounds/
    - assets/icons/splash.png